name: nop_db
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.2
  nop:
    git:
      url: https://github.com/sersr/nop.git
  nop_annotations:
    git:
      url: https://github.com/sersr/nop_annotations.git
dependency_overrides:
  nop:
    path: ../nop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0